import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Week 3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <Link href="about">About</Link>
          </p>
          <div>

          </div>
        </div>



        <div className={styles.grid}>Business Degrees:
          {
            information && information.map((info, index) => {
              if (info.department === "Business") {

                return (
                  <Card key={index} degree={info.degree} colour="#FF9FE5" font="15.6px" />
                )
              }
            })
          }

          <div className={styles.grid}>Computing Degrees:</div>
          {
            information && information.map((info, index) => {
              if (info.department === "Computing") {

                return (
                  <div key={index}>{info.degree}</div>
                )
              }
            })
          }

        </div>
      </main>
    </>
  )
}
